### ISSUE TITLE
Assumes .kube/config client-certificate is the raw cert

### ISSUE THREAD

**Issue by jason-kane** [LeastAuthority/txkube#120]
```  File "/usr/local/lib/python2.7/dist-packages/txkube/_network.py", line 86, in network_kubernetes_from_context
    [client_cert] = parse(user[u"client-certificate"].bytes())
ValueError: too many values to unpack
```

user["client-certificate"] by default contains a path to a cert file, not embedded cert file contents.

**Comment by jason-kane** [comment]
I'm wrong, what it doesn't like is a cert chain.

**Comment by exarkun** [comment]
Thanks for the report @jason-kane .  Do you think you could have a look at the pull request and see if it addresses the issue for you?
