### ISSUE TITLE
Certificate chain generation is incorrect in test_authentication.test_ordering

### ISSUE THREAD

**Issue by jlitzingerdev** [LeastAuthority/txkube#140]
There are three issues:
1.  The generated certificates in test_authentication.test_ordering are not signed as intended.  Specifically, instead of each generated key's public key being placed in the generated certificate, only a_key's public key is added.
2.  The private key used to sign the certs is always a's key.
3.  The serial number is always the same for each cert.

This was discussed briefly here:
https://twistedmatrix.com/pipermail/twisted-web/2017-July/005308.html

**Comment by jlitzingerdev** [comment]
The fixes seem fairly straightforward:
1.  Use the value passed in pubkey/privkey parameters later in the test.
2.  Generate a random number for the serial number.

Will submit a PR shortly.

**Comment by exarkun** [comment]
Fixed by #141
